sudo: required
dist: trusty
language: python
python:
  - "3.6.0"
env:
  - MY_OCTOCONF=".travis_octoconf.conf"
addons:
  apt:
    packages:
      - lame
      - aria2
before_install:
  - sudo add-apt-repository ppa:flexiondotorg/audio -y
  - sudo apt-get update
  - sudo apt-get install mp3gain -y
  - sudo apt-get install libtag1-dev -y
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - aria2c http://www.sample-videos.com/audio/mp3/wave.mp3
  - aria2c http://www-mmsp.ece.mcgill.ca/documents/audioformats/wave/Samples/Microsoft/8_Channel_ID.wav
script:
  - coverage run --source="." tests.py
after_success:
  - coveralls
