language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
addons:
  apt:
    packages:
      - faad
      - flac
      - lame
      - mp3gain
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python tests.py
after_success:
  - coveralls
